machine:
  yarn:
    version: 1.6.0

dependencies:
  pre:
    - rm -rf node_modules

test:
  override:
    - yarn run build
    - yarn run test:ci -- --coverage
    - yarn run test:server
  post:
    - mv ./coverage ${CIRCLE_ARTIFACTS}

deployment:
  dev:
    branch: /^(chore|dev|fix).*/
    commands:
      - git push -f git@heroku.com:${HEROKU_APP_DEV}.git ${CIRCLE_BRANCH}:master
  staging:
    branch: master
    heroku:
      appname: ${HEROKU_APP_PROD}
  production:
    branch: master
    commands:
      - |
        cat >~/.netrc <<EOF
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_TOKEN
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_TOKEN
        EOF
      - chmod 600 ~/.netrc # Heroku cli complains about permissions without this
      - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - git push git@heroku.com:${HEROKU_APP_PROD}.git $CIRCLE_SHA1:refs/heads/master
      - heroku run rake db:migrate --app xtunes-client:
          timeout: 400 # if your deploys take a long time